### ISSUE TITLE
tiled has a breaking tag

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/tiled-template#2]
See [`tiled` tag](https://github.com/bluesky/tiled/releases), [v0.1.0a104](https://github.com/bluesky/tiled/releases/tag/v0.1.0a104) is not backwards-compatible with clients.

Update to this tag but change the default port to 8020 (if it is available).

Noted in https://github.com/BCDA-APS/gemviz/issues/53

**Comment by prjemian** [comment]
Need to re-learn how to deliver file directories (with custom, local Python support).

**Comment by prjemian** [comment]
Added this section to `config.yml`:

```yaml
  - path: nexus
    tree: files
    args:
      directory: /home/prjemian/Documents/projects/BCDA-APS/tiled-template/dev_data/hdf5
      key_from_filename: tiled.adapters.files:identity
      mimetype_detection_hook: custom:detect_mimetype
      mimetypes_by_file_ext:
        .h5: application/x-hdf5
```

then try to start server:

```bash
Using configuration from /home/prjemian/Documents/projects/BCDA-APS/tiled-template/config.yml
Traceback (most recent call last):

  File "/home/prjemian/.conda/envs/tiled-test/bin/tiled", line 8, in <module>
    sys.exit(main())
             ^^^^^^

  File "/home/prjemian/.conda/envs/tiled-test/lib/python3.11/site-packages/tiled/commandline/_serve.py", line 563, in serve_config
    web_app = build_app_from_config(
              ^^^^^^^^^^^^^^^^^^^^^^

  File "/home/prjemian/.conda/envs/tiled-test/lib/python3.11/site-packages/tiled/server/app.py", line 839, in build_app_from_config
    kwargs = construct_build_app_kwargs(config, source_filepath=source_filepath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/prjemian/.conda/envs/tiled-test/lib/python3.11/site-packages/tiled/config.py", line 124, in construct_build_app_kwargs
    raise Exception(

Exception: The way that tiled serves files has changed.

See documentation section "Serve a Directory of Files".
```

**Comment by prjemian** [comment]
[Serve a Directory of Files](https://blueskyproject.io/tiled/tutorials/serving-files.html#serve-a-directory-of-files)

This section has no documentation regarding the `config.yml` file.

**Comment by prjemian** [comment]
[The tiled repo has example configuration files](https://github.com/bluesky/tiled/tree/main/example_configs).

But none of them describe a `config.yml` file that exports a tree of files.

@danielballan - I need some advice here.

**Comment by prjemian** [comment]
See this section: https://blueskyproject.io/tiled/explanations/specialized-formats.html

**Comment by prjemian** [comment]
These steps to create and index the directory:

```bash
    tiled catalog init catalog.db
    PYTHONPATH=. \
        tiled catalog register \
        catalog.db \
        --verbose \
        --ext '.nx5=application/x-hdf5' \
        --ext '.nexus.hdf5=application/x-hdf5' \
        --mimetype-hook 'custom:detect_mimetype' \
        --adapter 'text/spec_data=spec_data:read_spec_data' \
        ./dev_data
```

then this content in the `config.yml` file:

```yaml
  - path: dev_data
    tree: tiled.catalog:from_uri
    args:
      uri: ./catalog.db
      readable_storage:
        - ./dev_data
      adapters_by_mimetype:
        text/spec_data: spec_data:read_spec_data
```

**Comment by prjemian** [comment]
> [The tiled repo has example configuration files](https://github.com/bluesky/tiled/tree/main/example_configs).
> 
> But none of them describe a `config.yml` file that exports a tree of files.

Because the code changed.  In short, need to index the directory and collect metadata from the files.  That goes into a SQLite file, say `catalog.db`.  Configure the server to use that catalog file to serve the directory of file content.  As needed, update the catalog file, either in total or by subdirectory or file content.

**Comment by prjemian** [comment]
Config file example: https://blueskyproject.io/tiled/explanations/specialized-formats.html#register-the-exporter
